//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fileupload2mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_add_user
    {
        public int id { get; set; }
        [Required(ErrorMessage ="Can't be Empty")]
        [RegularExpression("[a-zA-Z]*$", ErrorMessage ="Text Only")]
        public string fullname { get; set; }
        [Required(ErrorMessage = "Can't be Empty")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage ="Invalid Email")]
        public string email { get; set; }
        [Required]
        [RegularExpression("^[0-9]{0,10}$", ErrorMessage = "Invalid Phone Number")]
        public string phone { get; set; }

        [Required(ErrorMessage = "Can't be Empty")]
        public string gender { get; set; }
        [Required(ErrorMessage = "Can't be Empty")]
        public string status { get; set; }
        [Required(ErrorMessage = "Can't be Empty")]
        public string username { get; set; }
        [Required(ErrorMessage = "Can't be Empty")]
        public string password { get; set; }
        [Required(ErrorMessage = "Can't be Empty")]
        public string profile { get; set; }
    }
}
